### PR TITLE
Added software permalinks for news items and all other containers

### PR DESCRIPTION
**Pull request by sabinmarcu**
## Reason for PR

Fixing Issue #1 
## Implementation

Without a backend, you have two choices for permalinks: 
1. Duplicating the `index.html` and moving it into folders, recreating the structure for each new item on the rss, or
2. Use the History API to generate it.

The current implementation makes use of the history API to simulate clicking actual links, and a shim before each step function (news, container, etc) to make sure it's properly initialized. At the same time, the html file was improved with a `base` element, that specifies what urls to use as base for relative paths (basically all resources used in the app), that's also used by the JS.

Either way, the biggest issue is redirecting requests (404s mostly) to the index.html. I took the liberty of assuming that the website will be hosted on gh-pages, and, as such, duplicated `index.html` into `404.html` to make it work. 
## Things to consider

Working with just one javascript file, without knowing where the website will be deployed, I had no way of knowing what the root address should be. As such, before deploying, I'd recommend changing the `base` element in the html files to suit the domain you're pushing to.
#### Example

| Address | Base |
| --- | --- |
| http://some.domain.com/ | / |
| http://domain.com/some/path | /some/path |
## Demo [over here](https://sabinmarcu.github.io/kokori/news/3)
# Hope it's useful

### CODE REVIEW

**Comment by marado** [comment]
Wow, thanks for the thorough pull request and explanation.

I'll review it later, but to answer your question already, this website is deployed at http://kokori.grogue.org , using an unchanged `git pull` of what comes from this repository.

**Comment by marado** [comment]
Hi @sabinmarcu :

I've taken a quick look on what you've done here, great job!
I'm temped to accept this PR in any case, but I'd like to ask you if you're interested in doing a couple of changes on it yourself:
- _remove the `.py` server_: since this code is replicated elsewhere, I'd rather not have potentially harmful code (code that opens ports being considered as such ;-)) laying around, just in case ;-);
- _deal with the `base` issue_: unlike previously, with the merge of this PR the website is going to stop working "in everyplace where it is deployed", needing to be configured. While optimally it would be great to have a way for this to work everywhere without changes, we should at least pull the configuration of `base` into a `config.js` or something like that, so that (a) the config file can be .gitignored and so not overridden, (b) it is obvious for an used that _there_ is some stuff that _needs_ to be configured in order for the website to work;
- _use "more permanent" permalinks_: as it is, we already have the main body of what we were trying to achieve in #1 . However, the fact that we're using sequential numbers for news entries means that once there's another news item published, all the links start pointing to the "wrong news entry". Maybe `pubDate` (from the RSS) could be used as an unique id for each news item?

**Comment by sabinmarcu** [comment]
Hi @marado 

Sure thing, I can make some more commits. I'll remove the `server.py`, of course. It was originally intended as a demo until I thought of github pages' 404 solution. I'll give it a thought on the RSS part (might need bigger changes on the code, but it's doable. I didn't want to change any of the base code structure, just add to it a bit). I guess the pushState can be done after the new news item is read :smile: 

The `base` issue is going to be the most annoying. The problem is grabbing a JS file regardless of where the entry point is (`/`, `/kokori/`, etc). For now, I guess I can set it to `/` so a deployment should be just fine, and I'll try to think of a solution. Perhaps an empty html file with the `base` already set, that would be different for `master` and `gh-pages`, that would load the rest of the content (and a `.gitattributes` or `.gitignore` file... the former case would be best, I guess).

Give me an hour :)

**Comment by sabinmarcu** [comment]
Hi @marado 

Back with some updates. Quite a bit of them.

First of all, I took the liberty of refactoring a lot of the code, and improving where I could: 
1. Split the code into respective parts (images in a folder, scripts in a folder, templates in a folder, etc).
2. To fix the `base` issue as best I can, I moved 99% of the application out of that `404.html` app and added a `.gitattributes` file specifying what merge strategy to use (basically when merging it will always keep the file at the state of this branch, not whatever you're merging into it... in short, it won't change).
3. I wrote a bit of code for workflow and util in the `utils.js` file, and initializing the app at `bootstrap.js`, making sure everything is loaded before starting the app.
4. I took all the messy HTML code in the JS file and split them into sections in the `templates` folder.

On future use, just use: 

``` js
utils.loadResource("templates/your_template.extension", function(data) { 
    // data == { html: "raw content", xml: "xml content, if parsed by the browser" }
});
// or 
utils.loadTemplate("your_template.extension", function(data) { 
    // data == { html: "raw content", xml: "xml content, if parsed by the browser" }
});
```
1. I revamped the XML parsing, and made permalinks of the form "sanitizedTitle_timestamp", just to make sure they're both readable, and unique. If you ever want to change the format of the permalinks, you can find that over [here](https://github.com/sabinmarcu/kokori/blob/gh-pages/js/utils.js#L48-L53).

Tested on both cases (`/`, `/somepath/`). As long as the base element is set in the `404.html` file on root, it's gonna be fine. This way, you can keep the `base` as `/kokori/` on `gh-pages`, and `/` for `master` when you deploy :smile: 

I'm sure you have some questions, but I hope you like what I did with the thing :+1:

**Comment by marado** [comment]
Thanks a lot, I like it! 
I'm on mobile now, but from what I've seen, this is going to allow me to have kokori.grogue.org keep git pulling the master branch automatically, which will be setted up as being the same as gh-pages in all but one file, which will have a different base value. Merges from gh-pages into master won't touch that file, and it only has skel logic, so it probably won't be updated often. The only change that will need to be done on the server is to say that the 404 page for that subdomain is 404.html.

If my interpretation is fine, then testing this will be quick, and I'll merge this PR as soon as I test it and all seems fine. I will only merge gh-pages into master after having the server point out the 404's to the correct page.

I am not sure when I'll have the time to actually test this, but in any case, thanks a lot for you work around here!

PS - and I hope you also found some time to press play and actually listen to some of the music kokori does ;-)

**Comment by marado** [comment]
@sabinmarcu I'm noticing you got rid of the background image of the website, was that on purpose?

**Comment by marado** [comment]
Thank you very much @sabinmarcu !
This is now merged, and will be pushed into `master` and the production server as soon as it is reconfigured (probably only needs an ErrorDocument directive).
If you still have the cycles to spare, there's an (easier) #hacktoberfest issue you could work on ( #4 ).

**Comment by sabinmarcu** [comment]
Hi, @marado. Sorry to bother you, but can you do me a small favor? 
I'm not 100% sure how they'll be counting the hacktoberfest PRs, but just for good measure, can you add the hacktoberfest label to this PR? I'll take a look at the other Issue, and figure it out, it's been a hectic month 😄

**Comment by marado** [comment]
Label added, even if it isn't needed for it to count. :-)

**Pull request merged**
